horovodrun -np 8 -H localhost:8 python train_seed.py --seed 2021 -m gigaNet_1
horovodrun -np 8 -H localhost:8 python train_seed.py --seed 2022 -m gigaNet_2
horovodrun -np 8 -H localhost:8 python train_seed.py --seed 2023 -m gigaNet_3
horovodrun -np 8 -H localhost:8 python train_seed.py --seed 2024 -m gigaNet_4
horovodrun -np 8 -H localhost:8 python train_seed.py --seed 2025 -m gigaNet_5
horovodrun -np 8 -H localhost:8 python train_seed.py --seed 2026 -m gigaNet_6
horovodrun -np 8 -H localhost:8 python train_seed.py --seed 2027 -m gigaNet_7
horovodrun -np 8 -H localhost:8 python train_seed.py --seed 2028 -m gigaNet_8
horovodrun -np 8 -H localhost:8 python train_seed.py --seed 2029 -m gigaNet_9
horovodrun -np 8 -H localhost:8 python train_seed.py --seed 2030 -m gigaNet_10
horovodrun -np 8 -H localhost:8 python train_seed.py --seed 2031 -m gigaNet_11
horovodrun -np 8 -H localhost:8 python train_seed.py --seed 2032 -m gigaNet_12
horovodrun -np 8 -H localhost:8 python train_seed.py --seed 2033 -m gigaNet_13
horovodrun -np 8 -H localhost:8 python train_seed.py --seed 2034 -m gigaNet_14
horovodrun -np 8 -H localhost:8 python train_seed.py --seed 2035 -m gigaNet_15
horovodrun -np 8 -H localhost:8 python train_seed.py --seed 2036 -m gigaNet_16
horovodrun -np 8 -H localhost:8 python train_seed.py --seed 2037 -m gigaNet_17
horovodrun -np 8 -H localhost:8 python train_seed.py --seed 2038 -m gigaNet_18
horovodrun -np 8 -H localhost:8 python train_seed.py --seed 2039 -m gigaNet_19
horovodrun -np 8 -H localhost:8 python train_seed.py --seed 2040 -m gigaNet_20
