horovodrun -np 8 -H localhost:8 python train_seed.py --seed 2021 -m gigaNet_simple_1
horovodrun -np 8 -H localhost:8 python train_seed.py --seed 2022 -m gigaNet_simple_2
horovodrun -np 8 -H localhost:8 python train_seed.py --seed 2023 -m gigaNet_simple_3
horovodrun -np 8 -H localhost:8 python train_seed.py --seed 2024 -m gigaNet_simple_4
horovodrun -np 8 -H localhost:8 python train_seed.py --seed 2025 -m gigaNet_simple_5
horovodrun -np 8 -H localhost:8 python train_seed.py --seed 2026 -m gigaNet_simple_6
horovodrun -np 8 -H localhost:8 python train_seed.py --seed 2027 -m gigaNet_simple_7
horovodrun -np 8 -H localhost:8 python train_seed.py --seed 2028 -m gigaNet_simple_8
horovodrun -np 8 -H localhost:8 python train_seed.py --seed 2029 -m gigaNet_simple_9
horovodrun -np 8 -H localhost:8 python train_seed.py --seed 2030 -m gigaNet_simple_10
horovodrun -np 8 -H localhost:8 python train_seed.py --seed 2031 -m gigaNet_simple_11
horovodrun -np 8 -H localhost:8 python train_seed.py --seed 2032 -m gigaNet_simple_12
horovodrun -np 8 -H localhost:8 python train_seed.py --seed 2033 -m gigaNet_simple_13
horovodrun -np 8 -H localhost:8 python train_seed.py --seed 2034 -m gigaNet_simple_14
horovodrun -np 8 -H localhost:8 python train_seed.py --seed 2035 -m gigaNet_simple_15
horovodrun -np 8 -H localhost:8 python train_seed.py --seed 2036 -m gigaNet_simple_16
horovodrun -np 8 -H localhost:8 python train_seed.py --seed 2037 -m gigaNet_simple_17
horovodrun -np 8 -H localhost:8 python train_seed.py --seed 2038 -m gigaNet_simple_18
horovodrun -np 8 -H localhost:8 python train_seed.py --seed 2039 -m gigaNet_simple_19
horovodrun -np 8 -H localhost:8 python train_seed.py --seed 2040 -m gigaNet_simple_20
